### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by Neo-Oli** [hr8/googleplay#3]
From the other issue, but now with much less people:

Do you mind tagging a new release? As far as I am aware, the last tagged release is v1.9.1 in the old-old repository and I am still on that version.

I also don't know if there are any meaningful changes since then, because the git history is lost.

**Comment by hr8** [comment]
a release was already tagged when you posted this issue:

https://github.com/hr8/googleplay/releases/tag/v1.0.0

I can tag a new release from current `main`, but its not really any different:

https://github.com/hr8/googleplay/compare/v1.0.0...main

note that the import path has changed:

https://github.com/hr8/googleplay/blob/5a97612dd6cd04538e008bf1169466b3a2837b1b/go.mod#L1

this way, if I have further account troubles, the import path will not have to change any more

**Comment by Neo-Oli** [comment]
I see. Thanks. I seem to have missed it because, for some reason, it's not in the sidebar of the main code view, where I expect these. Perhaps because it's only a _Tag_ and not a  Github _Release_ . This page is empty: https://github.com/hr8/googleplay/releases.
This way people who only _Watch_ the repository for releases will not get notified.
![Screenshot 2023-01-10 at 00-14-54 Tag a release · Issue #3 · hr8_googleplay](https://user-images.githubusercontent.com/7983745/211427181-fb6f5cd4-debf-4a66-9462-e2a662eca030.png)

**Comment by hr8** [comment]
thanks for the feedback. I could create a release for every tag, but its kind of pointless. Releases are really only useful if I upload a build. I previously uploaded some builds on the old repo. I might do that again, but I would like my account to stabilize before I do that. In general, its a bad idea to assume this is the "current version":

https://github.com/hr8/googleplay/releases

that is the location for the current **build**, but since releases can be missing from some tags (or all tags in my case), the best place to find "current version" is here:

https://github.com/hr8/googleplay/tags

this is annoying, as GitHub will only notify **releases** and not **tags**, but that is a GitHub problem, not something I am doing wrong.
